name: CI

on:
  push:
      branches: [master]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        run: |
          git -C $(brew --prefix)/Homebrew apply $(realpath brew.diff)
          brew reinstall $(brew deps zsh) zsh
          file $(brew --prefix zsh)/bin/zsh
