name: CI

on:
  push:
      branches: [master]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        run: |
          brew update
          brew install zsh
          make test
